### ISSUE TITLE
README - minor correction

### ISSUE THREAD

**Issue by Tim-K-DFW** [jlm429/bettermdptools#1]
2nd paragraph says (emphasis added):
> Here, blackjack.convert_state_obs changes the 3-tuple into a discrete space with *290* states by concatenating player states *0-28* (hard 4-21 & soft 12-21) with dealer states 0-9 (2-9, ten, ace).

This appears to be a typo. There are 280 total states, because player states range from 0 to 27 (not 0 to 28): 18 states for hard 4-21 (so 0, 1, ..., 17) and 10 states for soft 12-21 (18, 19, ...27).

**Comment by jlm429** [comment]
Thanks.
