### ISSUE TITLE
Policy iteration - can be improved to run faster and aligned with Sutton-Barto

### ISSUE THREAD

**Issue by Tim-K-DFW** [jlm429/bettermdptools#2]
![image](https://user-images.githubusercontent.com/8753831/202861896-de7f296e-265b-42dc-8454-7b80aea34642.png)

... but the current implementation [starts every evaluation with zero utility values](https://github.com/jlm429/bettermdptoolbox_v2/blob/eb79995b8082de801b8e4154d42af8f7ca455cb3/bettermdptoolbox/planning.py#L60).

A trivial code update sped things up by 1.5x in several experiments.

**Comment by jlm429** [comment]
Can you open a PR?  I'll take a look.
