### ISSUE TITLE
No module `bettermdptools.envs.binning` : @bit-wrangler @jlm429

### ISSUE THREAD

**Issue by ethankoch4** [jlm429/bettermdptools#33]
@bit-wrangler @jlm429 

I am getting an error on line 6 because there is no `bettermdptools.envs.binning` module

In the future PRs should likely have some sort of unit test or verification assistance to some degree - currently this is broken

_Originally posted by @ethankoch4 in https://github.com/jlm429/bettermdptools/pull/32#discussion_r1875058788_

**Comment by bit-wrangler** [comment]
https://github.com/jlm429/bettermdptools/pull/35

**Comment by bit-wrangler** [comment]
I was asked to split up a different pull request and in the rush to get it done forgot to include it
