### ISSUE TITLE
Acrobot currently not working

### ISSUE THREAD

**Issue by ethankoch4** [jlm429/bettermdptools#34]
This is currently not functional for me. I am getting the error:
```
Traceback (most recent call last):
  File "bettermdptools/envs/acrobot_wrapper.py", line 67, in __init__
    acro = DiscretizedAcrobot(angular_resolution_rad=angular_resolution_rad,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DiscretizedAcrobot.__init__() got an unexpected keyword argument 'timestep_sec'
```

@abust005 @jlm429

_Originally posted by @ethankoch4 in https://github.com/jlm429/bettermdptools/pull/27#discussion_r1875059536_

**Comment by bit-wrangler** [comment]
I have, in my (biased, obviously) opinion, a better implementation of acrobot with probabilistic transitions and caching of those transitions (since they can take hours to compute for larger problems), but I don't want to trample the other person's implementation. Maybe a separate ProbabilisticAcrobot model?

**Comment by ethankoch4** [comment]
In my unbiased opinion I think a library user would prefer a single ideal implementation instead of two; leaving them unsure of which to use, as long as you can accomplish the same thing with both

**Comment by bit-wrangler** [comment]
My probabilistic transitions are based on sub-sampling of each state. Technically, all the user would have to do is set the number of samples to 1 (use the "center" of each state), which would turn the model into the simplified deterministic case.

**Comment by abust005** [comment]
@ethankoch4 Thank you for pointing this out! I've opened PR #38 to address this. Hopefully the graders haven't tried to run my assignment yet, as that means that it would've failed, I suspect. Not sure how that got through.

@bit-wrangler I wholly encourage any changes you feel are better.
